package com.elkrrai.techtalk.data.local.db.utils

import androidx.room.RoomDatabaseConstructor
import com.elkrrai.techtalk.data.local.db.AppDatabase

/** The actual is generated by the Room KSP compiler per platform. */
@Suppress("KotlinNoActualForExpect")
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase> {
    override fun initialize(): AppDatabase
}
